language: node_js
node_js: stable
script:
- npm install --prefix=webpack-study
- npm run build --prefix=webpack-study
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
local-dir: ./webpack-study/build
