language: node_js
node_js: stable
before_script: cd ./webpack-study
script:
- npm install
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./webpack-study/dist
  on:
    branch: master
